### ISSUE TITLE
Rename generated `index.tsx` to `.ts`

### ISSUE THREAD

**Issue by rabelloo** [onfido/castor-icons#272]
In order for builders not to need to support `jsx`, simply renaming the index file should make the constants and types usable without it.

https://github.com/onfido/castor-icons/blob/main/scripts/build.ts#L172

**Comment by josokinas** [comment]
Components would still be a `tsx/jsx`, would this make any difference?

**Comment by rabelloo** [comment]
I don't think it would, only the types would be used by `tsc` I believe.
